### ISSUE TITLE
REST API ?

### ISSUE THREAD

**Issue by paulkeogh** [mahendra-panchal/hyperledger-fabric-test-network#1]
Can you please clarify if this installation includes a REST API ? (similar to the balance transfer sample from the Hyperledger git repo)

**Comment by emptybytes** [comment]
No this installation not include any REST API.

You have to test chain code  through command line.

Balance transfer sample have enabled fabric-ca so All communication to the Hyperledger Fabric CA server is happen via REST APIs.
